dockerfile changes

diff --git a/bin/ovpn_otp_user b/bin/ovpn_otp_user
--- a/bin/ovpn_otp_user
+++ b/bin/ovpn_otp_user
@@ -4,18 +4,18 @@
 # Generate OpenVPN users via google authenticator
 #
 
-if [ -z $1 ]; then
-    echo "Usage: ovpn_otp_user USERNAME"
+if ! source "$OPENVPN/ovpn_env.sh"; then
+    echo "Could not source $OPENVPN/ovpn_env.sh."
     exit 1
 fi
 
-# Server name is in the form "udp://vpn.example.com:1194"
-if [[ "$OVPN_SERVER_URL" =~ ^((udp|tcp)://)?([0-9a-zA-Z\.\-]+)(:([0-9]+))?$ ]]; then
-    OVPN_PROTO=${BASH_REMATCH[2]};
-    OVPN_CN=${BASH_REMATCH[3]};
-    OVPN_PORT=${BASH_REMATCH[5]};
-else
-    echo "Need to pass in OVPN_SERVER_URL in 'proto://fqdn:port' format"
+if [ "x$OVPN_OTP_AUTH" != "x1" ]; then
+    echo "OTP authentication not enabled, please regenerate configuration using -2 flag"
+    exit 1
+fi
+
+if [ -z $1 ]; then
+    echo "Usage: ovpn_otp_user USERNAME"
     exit 1
 fi
 
@@ -31,4 +31,3 @@ else
     google-authenticator --time-based --disallow-reuse --force --rate-limit=3 --rate-time=30 --window-size=3 \
         -l "${1}@${OVPN_CN}" -s /etc/openvpn/otp/${1}.google_authenticator
 fi
-
